eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://usr:pass1234@103.129.200.58:9110/eureka/
  instance:
    #hostname: localhost
    #prefer-ip-address: true
    #instance-id: ${eureka.instance.hostname}:${server.port}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    

#microservice:
  #acc-ca-service:
    #endpoints:
      #endpoint:
        #uri: http://fas-service/acc-ca/get-acc-ca-list
