eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9110/eureka/
  instance:
    hostname: localhost
    

#microservice:
  #acc-ca-service:
    #endpoints:
      #endpoint:
        #uri: http://fas-service/acc-ca/get-acc-ca-list
